/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_1024993_6[] = { 0, 13, 26 };

// (before - mean) / scale
const float ei_classifier_anom_scale_1024993_6[3] = { 9307.347393832697, 1991.4758640189716, 4762.635831041932 };
const float ei_classifier_anom_mean_1024993_6[3] = { 12297.508865290674, 2342.34037077975, 4207.485361950151 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_1024993_6[32] = {
	{ ( float[3] ) { -1.3117815256118774, -1.1370502710342407, -0.8590714931488037 }, 0.036587583443096636 },
	{ ( float[3] ) { -0.06601595133543015, -0.8049179911613464, -0.1411438286304474 }, 0.2793342536019082 },
	{ ( float[3] ) { -0.22943441569805145, -0.8174763321876526, -0.44464948773384094 }, 0.2321100053763373 },
	{ ( float[3] ) { 1.4859135150909424, 1.2046648263931274, 2.4902560710906982 }, 0.39227862725406526 },
	{ ( float[3] ) { -1.1460076570510864, 2.4483766555786133, -0.5998328924179077 }, 0.2455836026604977 },
	{ ( float[3] ) { -0.4852831959724426, -0.8245465159416199, -0.427798330783844 }, 0.38916100917351615 },
	{ ( float[3] ) { -1.1639295816421509, 1.524794578552246, -0.6040686964988708 }, 0.28307027770663634 },
	{ ( float[3] ) { -1.2418516874313354, 0.9328207969665527, -0.5937559008598328 }, 0.2854515219428429 },
	{ ( float[3] ) { -0.04881368950009346, -0.7672709822654724, -0.39120781421661377 }, 0.20862523134307734 },
	{ ( float[3] ) { 0.774745762348175, -0.1712731420993805, -0.009466201066970825 }, 0.25748734759903236 },
	{ ( float[3] ) { 0.6159825325012207, 0.30419135093688965, -0.1689583659172058 }, 0.300701936097089 },
	{ ( float[3] ) { 0.5780127644538879, 0.07012766599655151, 0.044343721121549606 }, 0.2697676465732943 },
	{ ( float[3] ) { 0.6557193994522095, -0.38072434067726135, -0.13203606009483337 }, 0.26616221785700894 },
	{ ( float[3] ) { 0.49840959906578064, -0.17075712978839874, -0.24338547885417938 }, 0.21835710111016218 },
	{ ( float[3] ) { -1.2607580423355103, 0.4729157090187073, -0.6549134850502014 }, 0.2244282363029488 },
	{ ( float[3] ) { 1.0091831684112549, 0.5152745842933655, -0.007813172414898872 }, 0.33747248012424474 },
	{ ( float[3] ) { 0.8931713104248047, -0.14312098920345306, 0.3763309419155121 }, 0.26627313137972114 },
	{ ( float[3] ) { 0.36316874623298645, -0.04472998529672623, -0.3337165415287018 }, 0.24641998168099546 },
	{ ( float[3] ) { -1.1509307622909546, 2.0050058364868164, -0.6024791598320007 }, 0.247347570150161 },
	{ ( float[3] ) { 1.199765920639038, 0.28975898027420044, 2.2177488803863525 }, 0.3849352012611086 },
	{ ( float[3] ) { 1.414892554283142, 0.259303480386734, 2.686880350112915 }, 0.4270312291853504 },
	{ ( float[3] ) { 0.8682029247283936, 0.01344049721956253, 0.5296470522880554 }, 0.2636576838848918 },
	{ ( float[3] ) { 0.7781201004981995, 0.03147165849804878, 1.8733322620391846 }, 0.6113435317393172 },
	{ ( float[3] ) { 0.8039632439613342, -0.555173397064209, -0.006867303047329187 }, 0.2814989110526984 },
	{ ( float[3] ) { -1.1937839984893799, 2.953737497329712, -0.5640619993209839 }, 0.36622983393713476 },
	{ ( float[3] ) { 0.7514292597770691, 0.04345503821969032, -0.16434325277805328 }, 0.2832432499318405 },
	{ ( float[3] ) { 1.4423649311065674, 0.5910269618034363, 2.2420382499694824 }, 0.3569868372836978 },
	{ ( float[3] ) { 1.1392254829406738, 0.0934021919965744, -0.02128743939101696 }, 0.2039108029841645 },
	{ ( float[3] ) { 1.5141068696975708, 0.8425944447517395, 2.6577601432800293 }, 0.3699320359574957 },
	{ ( float[3] ) { 1.4118635654449463, -0.011197910644114017, 2.39884352684021 }, 0.34730845032262136 },
	{ ( float[3] ) { 1.630590558052063, 1.7237337827682495, 2.866023063659668 }, 0.29685634948238776 },
	{ ( float[3] ) { -1.2587910890579224, 0.056760091334581375, -0.6808652877807617 }, 0.38596545964094786 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
