/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_1024993_6[] = { 0, 13, 26 };

// (before - mean) / scale
const float ei_classifier_anom_scale_1024993_6[3] = { 7317.092431851854, 1301.6415868011006, 5145.322418712466 };
const float ei_classifier_anom_mean_1024993_6[3] = { 10553.43712015412, 2100.1012448568354, 12683.876725779779 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_1024993_6[32] = {
	{ ( float[3] ) { -0.6938844919204712, -0.590791642665863, 0.550434410572052 }, 0.5835073813911547 },
	{ ( float[3] ) { -0.6836394667625427, -0.5299604535102844, 1.1291704177856445 }, 0.45981071130733736 },
	{ ( float[3] ) { 1.562130093574524, -0.0774020254611969, -1.7039843797683716 }, 0.4951703378677359 },
	{ ( float[3] ) { 1.894675850868225, 0.3491010069847107, 0.29440590739250183 }, 0.473759611336735 },
	{ ( float[3] ) { 1.459506630897522, 1.058964490890503, 1.2205517292022705 }, 0.39516372091282526 },
	{ ( float[3] ) { -0.9566248059272766, -1.0485889911651611, -0.34288039803504944 }, 0.3687827010765199 },
	{ ( float[3] ) { -0.669623613357544, -0.14131689071655273, 0.9422021508216858 }, 0.491499894170877 },
	{ ( float[3] ) { 1.6991878747940063, 2.2781007289886475, 0.03448203578591347 }, 0.7581480870344537 },
	{ ( float[3] ) { -0.3356338143348694, 0.08309763669967651, 1.051634669303894 }, 0.6103390238195983 },
	{ ( float[3] ) { 0.5691958665847778, 0.4500485956668854, -1.3588002920150757 }, 0.6344148815725634 },
	{ ( float[3] ) { 0.5624582767486572, -0.5582482814788818, -1.3044726848602295 }, 0.4832089637345232 },
	{ ( float[3] ) { 1.5782184600830078, 1.2750872373580933, -0.11035379022359848 }, 0.653677599302826 },
	{ ( float[3] ) { -0.8578764200210571, -0.8952441811561584, 0.16072174906730652 }, 0.6111873913845567 },
	{ ( float[3] ) { 1.089212417602539, 0.12238100916147232, -0.36181899905204773 }, 0.5306665929158408 },
	{ ( float[3] ) { 1.0557668209075928, 0.7351845502853394, -0.6111654043197632 }, 0.493144320177523 },
	{ ( float[3] ) { -1.0609207153320312, -1.0686194896697998, -0.9641948938369751 }, 0.36983388151769875 },
	{ ( float[3] ) { 0.8702577948570251, 0.2512693405151367, -0.8046561479568481 }, 0.582569494865901 },
	{ ( float[3] ) { -0.24197417497634888, 1.742626667022705, 1.65913724899292 }, 0.4043026857666936 },
	{ ( float[3] ) { -1.0504815578460693, -0.8075694441795349, -0.6635602712631226 }, 0.44717271105099615 },
	{ ( float[3] ) { -0.12979616224765778, 1.1835622787475586, 1.7495962381362915 }, 0.36533425045639095 },
	{ ( float[3] ) { -1.1798136234283447, -1.102850317955017, -1.4148554801940918 }, 0.5863395792865961 },
	{ ( float[3] ) { 1.661208152770996, 0.4359815716743469, -0.9521886110305786 }, 0.5441682997023501 },
	{ ( float[3] ) { 1.6456286907196045, 0.604669988155365, -0.1626906394958496 }, 0.5541914328456717 },
	{ ( float[3] ) { -1.3600338697433472, -1.4370869398117065, -2.2537753582000732 }, 0.8934727227762427 },
	{ ( float[3] ) { -0.1158071756362915, 2.404100179672241, 1.7600481510162354 }, 0.28818288673150066 },
	{ ( float[3] ) { 1.0016858577728271, 1.6147040128707886, -0.4498926103115082 }, 0.31711863148144986 },
	{ ( float[3] ) { -0.415487140417099, 1.343314290046692, 1.2246873378753662 }, 0.2875854761725213 },
	{ ( float[3] ) { 0.20462778210639954, -0.7586753368377686, -1.8887889385223389 }, 0.672109526104743 },
	{ ( float[3] ) { 0.40766122937202454, 0.8289111852645874, -0.6839788556098938 }, 0.5369074337365886 },
	{ ( float[3] ) { 0.9908358454704285, -0.5205740332603455, -0.5191260576248169 }, 0.5344990951771534 },
	{ ( float[3] ) { 1.1154708862304688, 1.993445634841919, -0.4052656292915344 }, 0.3653794250426547 },
	{ ( float[3] ) { -0.3487599790096283, 0.8146058917045593, 1.2474570274353027 }, 0.33376570751613327 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
